# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
# SPDX-License-Identifier: Apache-2.0

# allows to freeze, i.e., disables build.rs
[GenerateFlag]
generate = true

# location of the local ros2 setup that shall be used to get message interface information e.g. "/root/repos/DLR/tester/install/setup.bash"
[LocalSetupScript]
local_setup_script = [  "../test_ws/install/setup.bash" ]   

# Quality of service
[QoS_Default]
history = "KeepLast"                            # Options: KeepAll, KeepLast, SystemDefault, Unknown
depth = 10                                      # integer for queue size
reliability = "Reliable"                        # Options: BestEffort, Reliable, SystemDefault
durability = "Volatile"                         # Options: TransientLocal, Volatile, SystemDefault, Unknown
deadline_ms = 0                             # in milliseconds
lifespan_ms = 0                             # in milliseconds
liveliness = "Automatic"                        # Options: Automatic, ManualByTopic, SystemDefault, Unknown
liveliness_lease_duration_ms = 0            # in milliseconds
avoid_ros_namespace_conventions = false         # set to false to use ROS prefix and true to not using ROS namespace prefixing

[QoS_RTLolaOutput] 
history = "KeepLast"                            # Options: KeepAll, KeepLast, SystemDefault, Unknown
depth = 10                                      # integer for queue size
reliability = "Reliable"                        # Options: BestEffort, Reliable, SystemDefault
durability = "Volatile"                         # Options: TransientLocal, Volatile, SystemDefault, Unknown
deadline_ms = 0                             # in milliseconds
lifespan_ms = 0                             # in milliseconds
liveliness = "Automatic"                        # Options: Automatic, ManualByTopic, SystemDefault, Unknown
liveliness_lease_duration_ms = 0            # in milliseconds
avoid_ros_namespace_conventions = false         # set to false to use ROS prefix and true to not using ROS namespace prefixing

[QoS_RTLolaService]
history = "KeepLast"                            # Options: KeepAll, KeepLast, SystemDefault, Unknown
depth = 10                                      # integer for queue size
reliability = "Reliable"                        # Options: BestEffort, Reliable, SystemDefault
durability = "Volatile"                         # Options: TransientLocal, Volatile, SystemDefault, Unknown
deadline_ms = 0                                 # in milliseconds
lifespan_ms = 0                                 # in milliseconds
liveliness = "SystemDefault"                    # Options: Automatic, ManualByTopic, SystemDefault, Unknown
liveliness_lease_duration_ms = 0                # in milliseconds
avoid_ros_namespace_conventions = false         # set to false to use ROS prefix and true to not using ROS namespace prefixing

# Topic messages that should be ignored
[Blacklist]
topics = [   "rcl_interfaces/msg/ParameterEvent", 
                "rcl_interfaces/msg/Log", 
                "px4_msgs/msg/DebugArray", 
                "px4_msgs/msg/DebugKeyValue", 
                "px4_msgs/msg/DebugVect", 
                "px4_msgs/msg/PositionSetpointTriplet",
                "px4_msgs/msg/VehicleTrajectoryBezier",
                "px4_msgs/msg/VehicleTrajectoryWaypoint",
                "tester_publisher/msg/topic_lidar_reflect",
                "px4_msgs/msg/Timesync"
            ]

# Location where the generated files shall be located
[Destination]
path = "src_generated/"
