# SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
# SPDX-License-Identifier: Apache-2.0

generate_file = true

# location of the local ros2 setup that shall be used to get message interface information e.g. "/root/repos/DLR/tester/install/setup.bash"
local_setup_script = [  "../test_ws/install/setup.bash" ]   

# Topic messages that should be ignored
blacklist = [   "rcl_interfaces/msg/ParameterEvent", 
                "rcl_interfaces/msg/Log", 
                "px4_msgs/msg/DebugArray", 
                "px4_msgs/msg/DebugKeyValue", 
                "px4_msgs/msg/DebugVect", 
                "px4_msgs/msg/PositionSetpointTriplet",
                "px4_msgs/msg/VehicleTrajectoryBezier",
                "px4_msgs/msg/VehicleTrajectoryWaypoint",
                "tester_publisher/msg/topic_lidar_reflect",
                "px4_msgs/msg/Timesync"
            ]
# Location where the generated files shall be located
dest_path_generation = "src_generated/"
