// SPDX-FileCopyrightText: 2023 German Aerospace Center (DLR)
// SPDX-License-Identifier: Apache-2.0

#Voltage board in V
float32 a0
#Voltage servo rail in V
float32 a1
#Voltage power module voltage(ADC0, POWER port) in V
float32 a2
#Voltage power module current(ADC1, POWER port) in V
float32 a3
#Voltage adc2(ADC port) in V
float32 a4
#Voltage adc3(ADC port) in V
float32 a5
#Read a0 failed
int32 a0_read_failed
#Read a1 failed
int32 a1_read_failed
#Read a2 failed
int32 a2_read_failed
#Read a3 failed
int32 a3_read_failed
#Read a4 failed
int32 a4_read_failed
#Read a5 failed
int32 a5_read_failed
int32 x1
int32 x2
int32 x3
